Features/enemy
BhavyamKrGoyal/Tank_MVC pull request #2
Opened 2019-01-30 12:28 UTC by BhavyamKrGoyal

With Enemy spawn and shootable

2019-01-31 06:48 UTC, mayankgrover requested changes

2019-01-31 06:48 UTC, mayankgrover commented on Assets/scripts/Enemy/Controller/ControllerBlueEnemy.cs
> +    public static implicit operator ControllerBlueEnemy(ControllerEnemy v)
what's this implicit operator? 
and v? (rename it properly even if its for 1 line of code - remember serial killer) :)

2019-01-31 06:48 UTC, mayankgrover commented on Assets/scripts/Enemy/Controller/ControllerRedEnemy.cs
> +public class ControllerRedEnemy
we don't need child classes for enemy controllers and models - custom data is controlled through different scriptable objects (SO)

2019-01-31 06:48 UTC, mayankgrover commented on Assets/scripts/Enemy/ScriptableEnemy.cs
> +    public GameObject enemyPrefab;
replace GO with EnemyView class

2019-01-31 06:48 UTC, mayankgrover commented on Assets/scripts/Enemy/View/ViewBlueEnemy.cs
> +public class ViewBlueEnemy : MonoBehaviour
no custom views needed for now since we don't have custom behavior yet

2019-02-01 05:21 UTC, BhavyamKrGoyal commented on Assets/scripts/Enemy/Controller/ControllerBlueEnemy.cs
> +    public static implicit operator ControllerBlueEnemy(ControllerEnemy v)
done

2019-02-01 05:21 UTC, BhavyamKrGoyal commented on Assets/scripts/Enemy/Controller/ControllerRedEnemy.cs
> +public class ControllerRedEnemy
Done

2019-02-01 05:21 UTC, BhavyamKrGoyal commented on Assets/scripts/Enemy/ScriptableEnemy.cs
> +    public GameObject enemyPrefab;
done

2019-02-01 05:21 UTC, BhavyamKrGoyal commented on Assets/scripts/Enemy/View/ViewBlueEnemy.cs
> +public class ViewBlueEnemy : MonoBehaviour
okay

2019-02-01 06:32 UTC, merged