With 3 Scenes start menu, Game scene and Game over scene
BhavyamKrGoyal/Tank_MVC pull request #4
Opened 2019-02-01 12:14 UTC by BhavyamKrGoyal

serviceUI and InputManager are throughout the game and UI is updated by ServiceUI each UI Screen have a view and a controller

2019-02-01 14:04 UTC, mayankgrover requested changes
namespaces are missing everywhere

2019-02-01 14:04 UTC, mayankgrover commented on Assets/scripts/Bullets/ServiceBullet.cs
> +
namespace

2019-02-01 14:04 UTC, mayankgrover commented on Assets/scripts/SingletonScene.cs
> +public class SingletonScene<T> : MonoBehaviour where T : MonoBehaviour
why is it called singletonscene?

2019-02-01 14:04 UTC, mayankgrover commented on Assets/scripts/SingletonScene.cs
> +        instance = FindObjectOfType<T>();
not handling duplicate instances? and why was there a need for another singleton base class? didnt you already have a singleton base class already

2019-02-01 14:04 UTC, mayankgrover commented on Assets/scripts/UI/View/ViewMainMenu.cs
> +    Button play;
setup buttons as serialized fields and use onclick unity events

2019-02-02 04:28 UTC, BhavyamKrGoyal commented on Assets/scripts/SingletonScene.cs
> +public class SingletonScene<T> : MonoBehaviour where T : MonoBehaviour
it will have a singleton in a particular scene not whole game

2019-02-02 04:29 UTC, BhavyamKrGoyal commented on Assets/scripts/SingletonScene.cs
> +        instance = FindObjectOfType<T>();
that had DontDestroyOnLoadLevel()

2019-02-02 04:29 UTC, BhavyamKrGoyal commented on Assets/scripts/UI/View/ViewMainMenu.cs
> +    Button play;
okay

2019-02-04 14:03 UTC, merged